SystemUI: Screenrecord: Remove screenRecorderMaxFramerate integer and put the int value directly
Since we get:

Error: cannot find symbol                                                         R.integer.config_screenRecorderMaxFramerate);
                         ^                  symbol:   variable config_screenRecorderMaxFramerate                                location: class integer
1 error

Signed-off-by: GXC 2356 <gxcdev2356@gmail.com>